Parse req
dai65527/webserv pull request #10
Opened 2021-03-24 03:14 UTC by TrainCoffeeBoy

requestの最初の１行であるrequest lineのparseの部分を作成しました。
Requestクラスの単体テストも行なっています。
parse requestのエラーをどう返すかが未定です。
exceptionを色々投げると楽かなと思って、一旦throw std::runtime_errorを投げる形で動作確認しました。

2021-03-24 07:56 UTC, dai65527 reviewed
途中ですが、さっきまでの内容も含め気付いた点をを書いておきます。

2021-03-24 07:56 UTC, dai65527 commented on CgiHandler.cpp
> +CgiHandler& CgiHandler::operator=(const CgiHandler& other) { return *this; }
#11 で消してしまいました。

2021-03-24 07:56 UTC, dai65527 commented on Request.cpp
> +  ;
typo?

2021-03-24 07:56 UTC, dai65527 commented on Request.hpp
> +  kind : std::string buf_; /*for temporary saving before parsing*/
defineは複数のヘッダで被ってコンパイルエラーの原因になりそうなので、避けた方がいいかもしれません。

2021-03-24 07:56 UTC, dai65527 commented on arch/class.dio
>      </diagram>
git のdiffが入っちゃってますね... resetすればOKかと思います。

2021-03-24 07:56 UTC, dai65527 commented on Request.cpp
> +  pos = parseRequestLine();
例外を使うならここをtryで囲った方がいいと思います。取り逃すとプログラムが止まってしまいますので...

2021-03-24 07:56 UTC, dai65527 commented on Request.cpp
> +    }
if文不要かもしれません。

2021-03-24 07:56 UTC, dai65527 commented on Request.cpp
> +  }
改行まで読み込めていない場合セグフォしますね。`buf_[pos] == '\0'`も追加した方がよいと思います。

2021-03-24 07:56 UTC, dai65527 commented on Request.cpp
> +  }
80行目と同様

2021-03-24 12:26 UTC, TrainCoffeeBoy commented
HTTP1.1 は return -2に修正しました。
status_code_をメンバに追加し、request lineでのerrorで400, 505を設定するようにしました。

2021-03-25 15:53 UTC, TrainCoffeeBoy commented
headerのparse部分を追加しました。headerのエラーチェックはまだやっていません。
Requestのconstructの時点で、課題で対応必要なheaderの分だけあらかじめkeyを用意しています。
parse時はそれ以外のものがきてもheaderに何も考えずに追加するようにしています（headerは任意のkeyが許されているので）。
Responseで使う時など、必須header以外は無視してしまえばいいかと思っています。

2021-03-25 16:13 UTC, TrainCoffeeBoy commented
hostの存在チェックだけ追加しました。

2021-03-26 01:23 UTC, dai65527 requested changes
確認しました。僭越ながらいろいろコメントしました。修正をお願いいたします！
確認点あればご連絡ください！

2021-03-26 01:23 UTC, dai65527 commented on Request.cpp
> +  headers_["www-authenticate"] = "";
初期化は不要かと思います。大部分は無視されてしまうので。不要なヘッダがあると検索効率が落ちてしまいます。map内での有無の確認は以降で簡単に行えるので！

2021-03-26 01:23 UTC, dai65527 commented on Request.cpp
> +**   1: continue to receive (will beß set to select again)
typo?

2021-03-26 01:23 UTC, dai65527 commented on Request.cpp
> +  if (!flg_request_line_) {
フラグ名がちょっとややこしい、と思ってしまいました。request lineのパースが終了してからフラグ立つならflg_request_line_endとかの方がわかりやすいかもしれません。
ヘッダーのパース→ボディと続くなら、parse_progress_みたいなパースの状態を保存する変数にしてもいいかもしれません。

2021-03-26 01:23 UTC, dai65527 commented on Request.cpp
> +    if ((pos_buf = getRequestLine()) == -1) {
リクエストラインの終わりを探す関数であれば、findRequestLineEndなどの方がわかりよいかもしれません。ちょっと戸惑いました。。。

2021-03-26 01:23 UTC, dai65527 commented on Request.cpp
> +      if (buf_.substr(pos, 4) == "\r\n\r\n") {
文字列比較なら`if (!buf_.compare(pos, 4, "\r\n\r\n"))`の方がよいかもしれません。

2021-03-26 01:23 UTC, dai65527 commented on Request.cpp
> +        return -2;
返り値とstatus_code_の両方で判断することになってしまいます。情報に齟齬があるとバグの原因になりそうなのでどちらかに統一した方が良いと思います。（前回のMTG通りでいけば返り値）

2021-03-26 01:23 UTC, dai65527 commented on Request.cpp
> +    }
- これもgetHeaderField よりfind~~の方がいいかもしれません。（getはしていないので）
- 毎回`\r\n\r\n` まで一度探しに行っていますが、1行ごとに格納していけば、毎回0から探しに行かなくて済むので早くなりそうです。（今回の修正は不要かと思いますが。）

2021-03-26 01:23 UTC, dai65527 commented on Request.cpp
> +  if (headers_["host"].empty()) {
mapの要素の存在確認は`headers_.find("host") != headers_.end()` の形式の方が良いと思います。map::operator=は内部的にinsert関数を読んでいるので、存在しなかった場合新しい要素が追加されてしまいます。
（コンストラクタで値をmapの要素を初期化しない方が良いと言ったのはこういう背景もあります）

2021-03-26 01:23 UTC, dai65527 commented on Request.cpp
> +    // } keyの前に空白を許すかちょっと微妙（RFC的にはダメだが）
nginxに合わせてしまえばいい気がします笑

2021-03-26 01:23 UTC, dai65527 commented on Request.cpp
> +    std::string key = buf_.substr(begin, buf_.find(":", begin) - begin);
`:` がないときに例外が投げられちゃいます。
findがnposを返して、それがsubstrに入ってしまうという流れかなと。
https://cpprefjp.github.io/reference/string/basic_string/find.html

substrに入れる前に値の確認が必要だと思います。

以下例外が発生するテストケース
```
TEST_F(test_parseRequest, headersNoColon) {
  request.buf_ =
      "HEAD /index.html HTTP/1.1\r\nHost "
      "localhost\r\nLocation Yokohama\r\n\r\n";
  EXPECT_EQ(request.parseRequest(), 0);
}
```

2021-03-26 01:23 UTC, dai65527 commented on Request.cpp
> +      *itr = std::tolower(*itr);
algorithmヘッダ内のtransformを使うと楽にかけそうです。

野良ブログの記事ですが...
https://minus9d.hatenablog.com/entry/20130119/1358603761

2021-03-26 01:23 UTC, dai65527 commented on Request.cpp
> +           (buf_[begin] == '\t' || buf_[begin] == ' ')) {
リクエスト内の他の部分では水平タブの確認はしてませんが、大丈夫なんでしたっけ。

2021-03-26 01:23 UTC, dai65527 commented on Request.cpp
> +        pos += 2;
細かいですが、else 不要かな？ それか{}で囲って欲しいです。（Normないので可読性をとりましょう笑）

2021-03-26 01:23 UTC, dai65527 commented on test/unit_test/ParseRequest/test_parseRequest.cc
> +
水平タブのケースとかも追加したいですね。追加して損はないのでどんどん入れていきましょう！
（こんなのとか？）
```
TEST_F(test_parseRequest, splittedheadersagain) {
  request.buf_ = "HEAD /index.html HTTP/1.1\r\nHost: ";
  EXPECT_EQ(request.parseRequest(), 1);
  request.buf_.append("localhost\r\nLocation:\t  \tYokoh");
  EXPECT_EQ(request.parseRequest(), 1);
  request.buf_.append("ama\r\nlanguage: \t\t");
  EXPECT_EQ(request.parseRequest(), 1);
  request.buf_.append("en-US\r\n\r\n");
  EXPECT_EQ(request.parseRequest(), 0);
  EXPECT_EQ(request.method_, "HEAD");
  EXPECT_EQ(request.uri_, "/index.html");
  EXPECT_EQ(request.headers_["host"], "localhost");
  EXPECT_EQ(request.headers_["location"], "Yokohama");
  EXPECT_EQ(request.headers_["language"], "en-US");
}
```

2021-03-26 02:26 UTC, TrainCoffeeBoy commented on Request.cpp
> +  if (!flg_request_line_) {
parse_progrees_いいですね。そうします。

2021-03-26 02:30 UTC, TrainCoffeeBoy commented on Request.cpp
> +    if ((pos_buf = getRequestLine()) == -1) {
確かに。名前変えます！

2021-03-26 02:30 UTC, TrainCoffeeBoy commented on Request.cpp
> +      if (buf_.substr(pos, 4) == "\r\n\r\n") {
思いつきませんでした。その方がいいですね。どうしても知ってる武器で戦おうとしてしまいます...（４２の弱点か)

2021-03-26 02:30 UTC, TrainCoffeeBoy commented on Request.cpp
> +        return -2;
statuscode削除しました

2021-03-26 02:38 UTC, TrainCoffeeBoy commented on Request.cpp
> +    // } keyの前に空白を許すかちょっと微妙（RFC的にはダメだが）
nginxはhostはダメですね。hostさえOKであれば他のkeyでは弾かれないみたいです。
許容しないようにします。

2021-03-26 02:39 UTC, TrainCoffeeBoy commented on Request.cpp
> +      *itr = std::tolower(*itr);
試したのですが、最後の引数にtolowerを入れるとコンパイル通らなかったです。
通るコンパイラものあるそうですが。

2021-03-26 02:40 UTC, TrainCoffeeBoy commented on Request.cpp
> +           (buf_[begin] == '\t' || buf_[begin] == ' ')) {
headerだけはHTB含むでした。request lineはSPのみでした。

2021-03-26 02:40 UTC, TrainCoffeeBoy commented on Request.cpp
> +        pos += 2;
囲います

2021-03-26 02:55 UTC, TrainCoffeeBoy commented on Request.cpp
> +    }
findに変えました。
pos_buf = pos_prev_;で前回parseしたところの位置を与えているので、毎回頭から見ているようにはなっていないと思います。

2021-03-26 03:00 UTC, TrainCoffeeBoy commented on Request.cpp
> +  if (headers_["host"].empty()) {
constructorでの初期化をやめて、合わせてfindを使うようにしました。

2021-03-26 03:13 UTC, TrainCoffeeBoy commented on Request.cpp
> +    std::string key = buf_.substr(begin, buf_.find(":", begin) - begin);
見つけていただき、ありがとうございます。
:の存在確認で一旦エラー処理します。
example.comだとすぐに400、NginxだとhostでなければOKですが、
rfc的にはexample.comだと思いますので、エラーで返します。

2021-03-26 03:29 UTC, dai65527 commented on Request.cpp
> +    }
あ、すみません。見逃してました。それならよいかなと思います！

2021-03-26 03:30 UTC, dai65527 commented on Request.cpp
> +    // } keyの前に空白を許すかちょっと微妙（RFC的にはダメだが）
空白も含めてkeyの内容としてるってことですかね。

2021-03-26 08:06 UTC, TrainCoffeeBoy commented on test/unit_test/ParseRequest/test_parseRequest.cc
> +
追加しました。

2021-03-26 08:08 UTC, TrainCoffeeBoy commented
queryのparseも実装しました。
queryはoptionalなので変な値が入っていてもURIが正しければ、リクエストを出した時点ではエラーにはならないようです。
あと、全体的なエラー処理でnginxやexample.comに合わせるところは合わせました（-1を返すか、-2を返すかというところ）

2021-03-26 12:44 UTC, dai65527 approved these changes
getterができたらマージします！

2021-03-26 12:44 UTC, dai65527 commented on Request.cpp
> +  while (buf_.c_str()[pos] != '\0' && buf_[pos] == ' ' && buf_[pos] != '\r') {
条件は、`while (buf_.c_str()[pos] == ' ') `のみでOKでは？

2021-03-26 12:44 UTC, dai65527 commented on Request.hpp
> +  std::map<std::string, std::string> query_;
queryのGetterが欲しいです。

2021-03-26 13:14 UTC, TrainCoffeeBoy commented on Request.cpp
> +  while (buf_.c_str()[pos] != '\0' && buf_[pos] == ' ' && buf_[pos] != '\r') {
ですね！勉強になりました。

2021-03-26 13:18 UTC, TrainCoffeeBoy commented on Request.hpp
> +  std::map<std::string, std::string> query_;
押忍！

2021-03-26 13:21 UTC, TrainCoffeeBoy commented
お願いましす！

2021-03-26 13:25 UTC, merged