Dev parse req body
dai65527/webserv pull request #13
Opened 2021-03-28 05:40 UTC by TrainCoffeeBoy

Bodyのparseを追加しました。

bodyの読み取りに移行するには、contente-lengthが0より大きい数字で指定されているのが必須ですので、
そのチェックを行ってからbodyをstoreするようにしています。

bodyのstoreはcontent-length分だけ読み込んで終了します。
このbyte数の計算にには\r\nなども含むようにしてあります(example.comの挙動に合わせた）。

content-lengthの指定がないHTTP411というエラーはbodyのstore前に返す必要があるので、
Session.cppに-3:HTTP411を追加して、recv自体のエラーを-4として修正しています。

他に、リファクタリングしているところもあります。

2021-03-28 12:34 UTC, dai65527 requested changes
コメントしました。MTGの通りです。

2021-03-28 12:34 UTC, dai65527 commented on Request.cpp
> +         itr != headers_["content-length"].end(); ++itr) {
find("")は毎回計算量がかかるので、一度だけの方がいいと思います。変数に保存しておいた方がいいかなと思います。

2021-03-28 12:34 UTC, dai65527 commented on Request.cpp
> +      body_ = buf_.substr(pos_begin_body_, pos - pos_begin_body_);
buf_erase(0, pos_begin_body_)として、buf_をbody_として使う方が余計なメモリを食わなくて良さそう。

2021-03-28 12:34 UTC, dai65527 commented on Session.cpp
>    } else if (ret == 0) {
リクエストヘッダのContent-SizeとClientMaxBodySizeを照らし合わせなくてはいけない。ヘッダ部のパースが完了したら、その情報を確認した上で、Configを読み取る（setupServerAndLocationConfigを流用してください）

2021-03-28 14:10 UTC, TrainCoffeeBoy commented on Request.cpp
> +      body_ = buf_.substr(pos_begin_body_, pos - pos_begin_body_);
buf_.erase(pos_begin_body_);
buf_.erase(pos - pos_begin_body_, pos);
で後ろ側もeraseすることで想定通りとなりました(content-length分だけbufに残すため)。

2021-03-28 15:29 UTC, TrainCoffeeBoy commented on Request.cpp
> +         itr != headers_["content-length"].end(); ++itr) {
find一回だけ行うように全体を修正しました。

2021-03-28 23:12 UTC, dai65527 commented on Request.cpp
> +      body_ = buf_.substr(pos_begin_body_, pos - pos_begin_body_);
なるほど！

2021-03-29 07:19 UTC, TrainCoffeeBoy commented on Session.cpp
>    } else if (ret == 0) {
setupServerAndLocationConfigを読んで、そのあとにgetterでClientMaxBodySizeを取得して比較することにしました。

2021-03-29 07:25 UTC, TrainCoffeeBoy commented
### 修正点
- return valueの-1をrecvのerrorに当てて、-4をHTTP400としました
- headers.find("content-length")の使用を1回だけにする為リファクタリングしました
- 413を返す処理を追加しました

### テスト

- test/unit_test/Sessionに413のチェックを行うテストを追加
- telnetでcontent-lengthとmax_body_sizeの判定をテストする為に、configファイル（has_maxbodysize* ）をmain, server, location用に作成しました。
以下のようにテストできます
`./nginDX configfiles/has_maxbodysize_location.conf`

`Session (🐳 :dev_parseReq_body) :$ telnet localhost 8888
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /fuga/ HTTP/1.1
host:localhost
content-length:30

error: 413Connection closed by foreign host.`

2021-03-29 08:26 UTC, dai65527 requested changes
お疲れ様です。確認、コメントしました。

- headerのパースが終わった際は、bodyがあっても無くても、configをloadするようにしたいです。
- 可読性について結構コメントしてしまいました。パーサが大きくなってきたので、少し読みづらくなってきて気になった点をコメントしました。余裕があれば直していただけると幸いです。

2021-03-29 08:26 UTC, dai65527 commented on Request.cpp
> +    content_length_ = static_cast<size_t>(atoi(itr_content_length->second.c_str()));
atoiでは無くft_atoulがいいかなと思います。
client_max_body_sizeはギガのオーダーまでいくので、わざわざunsigned long型にしています。
content_lengthヘッダもそれに合わせて、unsigned longにした方がいいと思います。

2021-03-29 08:26 UTC, dai65527 commented on Session.cpp
> +  // 0:received all, 1:continue
ちょっとみづらいです...
ちょっと長いですが、このような形になりますか？
もっと長くなるのであればマクロかenumを使った方がいいかもしれません。

```
  0: continue to read
  1: received all (go to next)
  2: parsed all header (to find config)
 -1: failed to recv
 -2, -3, -4: invalid request
    -2: 400
    -3: 411
    -3: 505
```

2021-03-29 08:26 UTC, dai65527 commented on Session.cpp
> +  } else if (ret == -3) {
- 順番がわかりにくい
- 返り値についてコメントあると嬉しいです
- L169のコメントも参照ください

2021-03-29 08:26 UTC, dai65527 commented on Session.cpp
> +    return 0;
return 不要

2021-03-29 08:26 UTC, dai65527 commented on Session.cpp
> +               main_config_.getClientMaxBodySize()) {
setupConfigAndCheckFunc的な別関数に切り出すか、何をしているかのコメントをつけていいただきたいです。
UNIT_TESTのマクロも絡んで少し見辛い気がします。

2021-03-29 08:26 UTC, dai65527 commented on Request.cpp
>      pos_buf = pos_prev_;
parse_progressに今何やっているかのコメント書いておくとあとで楽かと思います。（それかマクロorEnumで名前をつける）

2021-03-29 08:26 UTC, dai65527 commented on Request.cpp
> +  if (content_length_ > 0 && parse_progress_ == 2) {
同上

2021-03-29 08:26 UTC, dai65527 commented on Request.cpp
> +    pos_prev_ = pos_begin_header_;
下で何もしないのであれば、ここでreturn 0した方がわかりやすいですね。

2021-03-29 08:26 UTC, dai65527 commented on Request.cpp
> +    return 42;
bodyを読まない場合でもConfigを読む必要はあります。
content_length_ == 0でも42を返して、L110の条件にあててreturn 0するか、Session.cppのL187あたりを工夫したら実現できるかなと思います。

2021-03-29 08:26 UTC, dai65527 commented on Request.cpp
> +    return 0;
return不要

2021-03-29 08:26 UTC, dai65527 commented on test/unit_test/ParseRequest/test_parseRequest.cc
> +  request.buf_ = "POST /index.html?a HTTP/1.1\r\nHost: ";
疲れが見えます...🙇‍♂️

2021-03-29 11:35 UTC, TrainCoffeeBoy commented on Request.cpp
> +    content_length_ = static_cast<size_t>(atoi(itr_content_length->second.c_str()));
unsigned long 承知です。

2021-03-29 12:45 UTC, TrainCoffeeBoy commented on Session.cpp
> +  // 0:received all, 1:continue
Request.hppに
```
#define FIN_PARSE_HEADER 2 //finished parsing header
#define CONTINUE_RECV 1 //continue to receive
#define FIN_RECV 0 // finished receiving
#define ERR_RECV -1 //fail syscall of recv
#define ERR_HTTP_VERSION -2 //HTTP505
#define ERR_LEN_REQUIRED -3 //HTTP411
#define ERR_BAD_REQUEST -4 //HTTP400

```を定義することにしました。

2021-03-29 12:46 UTC, TrainCoffeeBoy commented on Session.cpp
> +  } else if (ret == -3) {
defineした値で書き換えました。順番も
#define FIN_RECV 0 // finished receiving
 が最後に来るようにしました。

2021-03-29 12:46 UTC, TrainCoffeeBoy commented on Session.cpp
> +    return 0;
deleteしました

2021-03-29 12:55 UTC, TrainCoffeeBoy commented on Session.cpp
> +               main_config_.getClientMaxBodySize()) {
別関数に切り出し、コメントを追加しました。
マクロはそのままです（もう少し結合するテストするよになったら、外します）

2021-03-29 12:58 UTC, TrainCoffeeBoy commented on Request.cpp
>      pos_buf = pos_prev_;
コメントにしておきました。

2021-03-29 13:00 UTC, TrainCoffeeBoy commented on Request.cpp
> +    pos_prev_ = pos_begin_header_;
この後、処理はそのまま下に降りて行きます。

2021-03-29 13:02 UTC, TrainCoffeeBoy commented on Request.cpp
> +    return 42;
42返して、Session側を工夫します。

2021-03-29 13:10 UTC, TrainCoffeeBoy commented on Request.cpp
> +    return 0;
deleted!

2021-03-29 13:11 UTC, dai65527 commented on Session.cpp
> +  // 0:received all, 1:continue
`REQ_`のようなprefixを用いると名前被りのミスがなくなる＆見やすくていいかもしれません。

2021-03-29 13:12 UTC, dai65527 commented on Session.cpp
> +  } else if (ret == -3) {
ありがとうございます！

2021-03-29 13:12 UTC, TrainCoffeeBoy commented on test/unit_test/ParseRequest/test_parseRequest.cc
> +  request.buf_ = "POST /index.html?a HTTP/1.1\r\nHost: ";
これは?a以降はクエリの取り損ないでURIとしてはスルーなので、テストは通るパターンになります。

2021-03-29 13:14 UTC, dai65527 commented on test/unit_test/ParseRequest/test_parseRequest.cc
> +  request.buf_ = "POST /index.html?a HTTP/1.1\r\nHost: ";
すみませんLneghtに対するツッコミでした...💦

2021-03-29 13:26 UTC, TrainCoffeeBoy commented on test/unit_test/ParseRequest/test_parseRequest.cc
> +  request.buf_ = "POST /index.html?a HTTP/1.1\r\nHost: ";
本当に疲れているようです...

2021-03-29 13:32 UTC, TrainCoffeeBoy commented on Session.cpp
> +  // 0:received all, 1:continue
REQ_つけました

2021-03-30 19:22 UTC, TrainCoffeeBoy commented
コメントをいただいたところ以外で、

- buf_をvector<char>にしました
- findBodyEndを書き直しました(DMのやりとり通りです）
-parseRequestLine内のheaderがないことによるerrror判定が想定どおりでなかったので直しました。

2021-03-31 02:04 UTC, dai65527 requested changes
コメントしました。

- vector<char>からstringへの要素追加はrangeコンストラクタ、append、insertなどを使うと良いと思います。
- 必要のない文字列のコピーが結構あったので、気付いたところコメントしています。気軽に新しいstringインスタンスを作ると、メモリの確保とコピーが全部走るので、かなり時間がかかってしまいます。
- （大変今更ですが、ヘッダのパースをvector<char>でやるのは結構大変そうですね。ヘッダはstringでbodyはvectorで、と言うのもありだったかもですね...）

2021-03-31 02:04 UTC, dai65527 commented on test/unit_test/Session/test_checkHTTP413.cc
> +    }
`vec.insert(vec.end(), str.begin(), str.end());` 一発でOKです！（stringも中身は同じcharなので）

2021-03-31 02:04 UTC, dai65527 commented on Request.cpp
> +  }
これでOKです

```
if (end > begin) {
    return std::string(&buf_[begin], &buf_[end]);
  }
  return "";
```

2021-03-31 02:04 UTC, dai65527 commented on Request.cpp
> +  }
これでOKです！

```
method_.assign(&buf_[0], &buf_[pos]);
```

2021-03-31 02:04 UTC, dai65527 commented on Request.cpp
> +    headers_[key] = value;
`headers_[key] = bufToString`でいいと思います。このままだと2回コピーが発生してしまいます。

2021-03-31 02:04 UTC, dai65527 commented on Session.cpp
> +  str = NULL;
メモリ確保→コピーはもったいなさすぎるので、

```
n = write(file_fd_, &(request_.getBuf()[0]), request_.getBuf().size());
```

で良いと思います。

2021-03-31 02:04 UTC, dai65527 commented on Session.cpp
> +  str = NULL;
C++11だとrequest_.getBuf().data()で先頭ポインタ取れるんですがね...

2021-03-31 02:04 UTC, dai65527 commented on Request.cpp
> +  return str_buf.compare(0, str_buf.length(), str);
一度コピーすると時間とメモリがもったいないので、直でループ回して比較する方が良いと思います。

2021-03-31 04:21 UTC, TrainCoffeeBoy commented on test/unit_test/Session/test_checkHTTP413.cc
> +    }
なるほど(ft_containerやってる人は違う！）

2021-03-31 04:30 UTC, TrainCoffeeBoy commented on Request.cpp
> +  }
動きますね！
&でiteratorが取れる？
それともpointerを引数としてiteratorの代わりに取れる？
この辺りがまだよくわかってないですね。

2021-03-31 04:33 UTC, TrainCoffeeBoy commented on Request.cpp
> +  }
これもpointerでいいんですね...

2021-03-31 04:35 UTC, TrainCoffeeBoy commented on Request.cpp
> +    headers_[key] = value;
bufToStringのreturnはstringなので、一旦インスタンスができるのは変わらないが、
=だと、左辺に代入するので、すぐにdestructされるって動きになってます？

2021-03-31 04:39 UTC, TrainCoffeeBoy commented on Session.cpp
> +  str = NULL;
＆を使って、char*のポインタが直接取れるんですね。知らないことがばかりです。
ありがとうございます。

2021-03-31 04:55 UTC, TrainCoffeeBoy commented on Request.cpp
> +  return str_buf.compare(0, str_buf.length(), str);
承知です。

2021-03-31 05:00 UTC, TrainCoffeeBoy commented
いただいたコメントの修正＋writeToCgiにも余分なメモリ確保があったので修正しました。
iteratorとpointerの扱いで理解できていないところがあり、
コメントに質問させていただいたので、教えてください（動作は確認できています）。

2021-03-31 05:06 UTC, dai65527 commented on Request.cpp
> +  }
イテレータってポインタみたいなものなので逆にポインタを使うこともできます！

2021-03-31 06:21 UTC, dai65527 commented on Request.cpp
> +    headers_[key] = value;
headers_[key]にすぐコピーされて消滅するものと思われます。

2021-03-31 06:23 UTC, dai65527 commented on Request.cpp
> +  }
すみません質問に答えられてなかったですね。&でchar*が取れるはずです

2021-03-31 06:26 UTC, dai65527 commented
Looks Good To Me!!!

2021-03-31 06:27 UTC, merged