Recreate mini webserv
dai65527/webserv pull request #2
Opened 2021-03-03 13:18 UTC by TrainCoffeeBoy

Class図に乗っ取り、hppファイルだけ作成しました。
HTTPStatusCodeはRFC7231にあって、HTTP/1.1で有効なものは全て加えてみました。
Length Required, HTTP Version Not Supportedなどtelenetからの動作だと必要そうだと思いました。

2021-03-04 03:18 UTC, dai65527 requested changes
お忙しい中作成ありがとうございました。
最新のクラス図を参照しつつ、各ソースへのコメントと以下を修正お願いします。

### 全体へのコメント
- インデントはスペース2つでお願いします。（https://ttsuki.github.io/styleguide/cppguide.ja.html#Spaces_vs._Tabs）
- 細かいですが、const参照を書く場合の順序は`const ClassName& instance_name` としてください（https://ttsuki.github.io/styleguide/cppguide.ja.html#Reference_Arguments）
- フォーマッタを使ってください。（波かっこの位置やインクルードの順序などが自動修正されます。）
- dioは更新されているので、削除するか、pullでmainブランチの内容に書き換えておいてください。コンフリクトが予想されます。

2021-03-04 03:18 UTC, dai65527 commented on CgiHandler.hpp
> +#define CGIHANDLER_HPP
重複してしまっています。
これがあると何もインクルードされなくなっちゃいますね...笑

2021-03-04 03:18 UTC, dai65527 commented on HttpStatusCode.hpp
> +typedef enum {
typedefではなく素直にこの形式でよいかと思います。

```
enum HttpStatusCode {
...
}
```

参考： https://ttsuki.github.io/styleguide/cppguide.ja.html#Enumerator_Names

2021-03-04 03:18 UTC, dai65527 commented on HttpStatusCode.hpp
> +  HTTP_426 = 426, /* Upgrade Required */
I'm a teapotがない...笑
https://developer.mozilla.org/ja/docs/Web/HTTP/Status/418

冗談として、未定義のものは必要に応じて追加していけばいいですかね。

2021-03-04 03:18 UTC, dai65527 commented on HttpStatusCode.hpp
> +/*   HttpStatusCode.hpp                                 :+:      :+:    :+:   */
これ欲しかったんです！！

2021-03-04 03:18 UTC, dai65527 commented on Webserv.hpp
> +		std::list<Server>		servers;
servers_

2021-03-04 03:18 UTC, dai65527 commented on Webserv.hpp
> +		virtual ~Webserv();
継承しないけどvirtual大事ですね笑

2021-03-04 03:18 UTC, dai65527 commented on Webserv.hpp
> +		int		loadConfig(std::string filename) const;
引数はconst参照渡しの方がいいかもしれません。

2021-03-04 03:18 UTC, dai65527 commented on Server.hpp
> +
defalut_location_configに対し、location_configs_リストも作成してください（クラス図参照）
以下のようなイメージです。

```
server {
  port 80;

  # default location config (serverに設定されているlocationにも設定可能なディレクティブたち)
  root /var/www/html;
  hoge fuga;

  location /hoge/ {
    # element of location_configs （ルートごとに指定されたlocationConfig）
    root /var/www/html;
    hoge fugafuga;
  }
}
```

2021-03-04 03:18 UTC, dai65527 commented on Server.hpp
> +		std::map<int, in_addr_t>	port_ip_;
ipアドレスとportを対応させるmapでしたが、課題を読み返して思ったのですが、ipを指定する必要はないかもしれません。単にlist<int> port_list_ などとしてもいいかもしれません。
MTGで議論させてください。

2021-03-04 03:18 UTC, dai65527 commented on Server.hpp
> +		LocationConfig&						getDefaultLocationConfig() const;
クラス図にある以下のメンバー関数を追加したいです。

- setDafaultLocationConfig(LocationConfig): void
- addToLocationConfig(): int
location_configs_ リストに要素を追加する
- configIsValid(): int
configが有効かどうか検証する関数
- isMatch(int, in_addr_t, string server_name): int
ポート、IP、サーバー名からserverが一致するか確認する関数

2021-03-04 03:18 UTC, dai65527 commented on Response.hpp
> +#endif /* RESPONSE_HPP */
最終行に改行を入れたいです。
http://hiroakiuno.hatenablog.com/entry/20070409/p1

2021-03-04 03:18 UTC, dai65527 commented on SessionStatus.hpp
> +typedef enum {
typedefではなく素直にこの形式でよいかと思います。

```
enum SessionStatus {
...
};
```

参考： https://ttsuki.github.io/styleguide/cppguide.ja.html#Enumerator_Names

2021-03-04 03:18 UTC, dai65527 commented on LocationConfig.hpp
> +  uint allowed_method_;
クラス図にuintって書いたのですが、uintって環境依存っぽいので、uint32_tにしていただきたいです...🙇‍♂️
bitflagなのでbit数が明示的かつ固定の方がいい気もします。

2021-03-04 03:18 UTC, dai65527 commented on LocationConfig.hpp
> +  std::string getRoot() const;
stringを返す物はconst std::string&でconst参照を返す方が良いと思います。（以下も同様）

2021-03-04 03:18 UTC, dai65527 commented on LocationConfig.hpp
> +  std::list<std::string> getIndex() const;
const参照返しの方が良いと思います。（こうするとcopyのコストがかかってしまうので）

2021-03-04 03:18 UTC, dai65527 commented on LocationConfig.hpp
> +  std::list<std::string> getCgiExtension() const;
上と同様

2021-03-04 03:18 UTC, dai65527 commented on LocationConfig.hpp
> +  void setAllowedMethod(std::string);
引数にクラスを持つ物はconst参照渡しにした方が良いと思います。（以下も）

2021-03-04 03:18 UTC, dai65527 commented on LocationConfig.hpp
> +  void setIndex(std::list<std::string>);
listごとsetすることはないと思います。indexの文字列を受け取るaddIndexなどの関数とした方がよいと思います。list::pushback() のラッパーのようなイメージですね。
（クラス図に明記できていませんでしたねすみません。🙇‍♂️）

2021-03-04 03:18 UTC, dai65527 commented on LocationConfig.hpp
> +  void setCgiExtension(std::list<std::string>);
setIndexと同様

2021-03-04 03:18 UTC, dai65527 commented on LocationConfig.hpp
> +  void setUploadStore(std::string);
上記と同様（const 参照渡し）

2021-03-04 03:18 UTC, dai65527 commented on Socket.hpp
> +		Session& 		acceptRequest() const;
Sessionではなく、accept済みのfdを返すようにしたいです。
Sessionのコントラクトはlist追加時に行いたいです。

2021-03-04 03:18 UTC, dai65527 commented on Socket.hpp
> +		void				init(int	port) const;
sockaddr_inなどを書き換えるので、const関数にはならないです。

2021-03-04 03:18 UTC, dai65527 commented on Session.hpp
> +}
セミコロン

2021-03-04 03:18 UTC, dai65527 commented on Session.hpp
> +		const LocationConfig&	config_;
const参照はconstructorで初期化しなきゃいけなかった気がします。（クラス図を書くときに忘れてましたすみません）
インスタンスを各セッションに持たせるのはもったいないので、constポインタで持たせる方がいいかもしれません。

2021-03-04 03:18 UTC, dai65527 commented on Session.hpp
> +		CgiHandler getCgiHandler() const;
クラスを返すgetterはconst参照を返す方が良いと思います。

2021-03-04 03:18 UTC, dai65527 commented on Session.hpp
> +		pid_t getCgiPid() const;
使う場面がないかもしれません。

2021-03-04 03:18 UTC, dai65527 commented on Session.hpp
> +		void	setConfig();
現状の構成だと、引数はconst list<ServerConfig>&かと思います
Request受信後に、Webserv::serversからの中からconfiglistを決定する流れですね。

2021-03-04 03:18 UTC, dai65527 commented on Session.hpp
> +		int	checkSelectedAndExecute()
引数は、fd_set型のポインタでないといけません。ポインタで受けて、それをFD_SETで書き換えるorFD_ISSETで確認する流れです。

2021-03-04 03:18 UTC, dai65527 commented on Session.hpp
> +		int readToFromFile() const;
タイポ？
おそらくconst関数にはならないです。（readした後responseに書き込むので）

2021-03-04 03:18 UTC, dai65527 commented on Session.hpp
> +		int sendResponse() const;
これもresponseの内容を書き換えるので、const関数にはならないと思います。

2021-03-04 03:18 UTC, dai65527 commented on Response.hpp
> +  size_t getRawResponse(char**) const;
引数リストには名前を入れて欲しいです。（可読性の面で。何を入れればいいのかわからなくなります。）

2021-03-04 03:18 UTC, dai65527 commented on Request.hpp
> +}
セミコロン

2021-03-04 03:18 UTC, dai65527 commented on Request.hpp
> +  std::string getBody() const;
クラスを返すgetterはconst参照返しの方が良いと思われます。

2021-03-04 03:18 UTC, dai65527 commented on CgiHandler.hpp
> +		int	cgi_output_fd_;
メンバ変数なので、"cgi_" 付けなくてもよいかもしれません。（クラス図そうなってましたね。すみません。）

2021-03-04 03:18 UTC, dai65527 commented on CgiHandler.hpp
> +};
以下の関数を追加したいです。（クラス図通り）

- createCgiProcess（プロセスのフォーク、パイプの作成）
- writeToCgi（cgiプロセスの標準入力に書き込む）
- finishWriting（cgiプロセスの標準入力に書きこむ物がなくなったときに読んで、パイプをcloseする）
- readFromCgi（cgiプロセスの標準出力から読み込む）

2021-03-04 11:53 UTC, dai65527 commented on Server.hpp
> +		std::map<int, in_addr_t>	port_ip_;
上記はhost名が指定された場合は、/etc/hostsの内容を読んでそれに対するIPをsocketのアドレスに指定することにする。だから、必要でした。

2021-03-04 14:58 UTC, TrainCoffeeBoy commented on CgiHandler.hpp
> +#define CGIHANDLER_HPP
done

2021-03-04 14:59 UTC, TrainCoffeeBoy commented on HttpStatusCode.hpp
> +typedef enum {
done

2021-03-04 14:59 UTC, TrainCoffeeBoy commented on HttpStatusCode.hpp
> +/*   HttpStatusCode.hpp                                 :+:      :+:    :+:   */
:)

2021-03-04 15:00 UTC, TrainCoffeeBoy commented on Webserv.hpp
> +		std::list<Server>		servers;
done

2021-03-04 15:00 UTC, TrainCoffeeBoy commented on Webserv.hpp
> +		virtual ~Webserv();
desune~

2021-03-04 15:01 UTC, TrainCoffeeBoy commented on Webserv.hpp
> +		int		loadConfig(std::string filename) const;
そうですね！

2021-03-04 15:05 UTC, TrainCoffeeBoy commented on Server.hpp
> +
見落としてました..

2021-03-04 15:44 UTC, TrainCoffeeBoy commented on Server.hpp
> +		LocationConfig&						getDefaultLocationConfig() const;
> addToLocationConfig(): int
> location_configs_ リストに要素を追加する
要素追加なので、引数は(const LocationConfig & location_config)という感じでいいですか？

あと、addPortToMap, addServerNameもクラス図にあったので足しました。

2021-03-04 15:50 UTC, TrainCoffeeBoy commented on Response.hpp
> +#endif /* RESPONSE_HPP */
Gyoi!

2021-03-04 15:50 UTC, TrainCoffeeBoy commented on SessionStatus.hpp
> +typedef enum {
gyoi

2021-03-04 15:52 UTC, TrainCoffeeBoy commented on LocationConfig.hpp
> +  uint allowed_method_;
gyoi

2021-03-04 15:52 UTC, TrainCoffeeBoy commented on LocationConfig.hpp
> +  std::list<std::string> getIndex() const;
OKです

2021-03-04 15:53 UTC, TrainCoffeeBoy commented on LocationConfig.hpp
> +  void setAllowedMethod(std::string);
ですね！勉強になります

2021-03-04 16:00 UTC, TrainCoffeeBoy commented on LocationConfig.hpp
> +  void setIndex(std::list<std::string>);
addIndexとして作成しました

2021-03-04 16:00 UTC, TrainCoffeeBoy commented on LocationConfig.hpp
> +  void setCgiExtension(std::list<std::string>);
こちらもaddCgiExtensionにしました

2021-03-04 16:13 UTC, TrainCoffeeBoy commented on Socket.hpp
> +		Session& 		acceptRequest() const;
なぜ急にsession出てきたのか、自分でも？？？

2021-03-04 16:14 UTC, TrainCoffeeBoy commented on Socket.hpp
> +		void				init(int	port) const;
initできないですね、これでは...

2021-03-04 16:34 UTC, TrainCoffeeBoy commented on Session.hpp
> +		const LocationConfig&	config_;
確かにconstだと初期化必須でしたね。pointerにしました。

2021-03-04 16:37 UTC, TrainCoffeeBoy commented on Session.hpp
> +		pid_t getCgiPid() const;
消しておきます。

2021-03-04 21:59 UTC, dai65527 commented on Server.hpp
> +		LocationConfig&						getDefaultLocationConfig() const;
> 要素追加なので、引数は(const LocationConfig & location_config)という感じでいいですか？
良いと思います！
ありがとうございます！

2021-03-05 00:19 UTC, TrainCoffeeBoy commented on Session.hpp
> +		int	checkSelectedAndExecute()
fdsでしたね...すみません

2021-03-05 00:20 UTC, TrainCoffeeBoy commented on Session.hpp
> +		int readToFromFile() const;
readという名前からつけてしまいました...外しました

2021-03-05 00:41 UTC, TrainCoffeeBoy commented on Session.hpp
> +		const LocationConfig&	config_;
と書いたものの、constついていると初期化してやらないといけないのは変わらないですね。
あと、ここをポインタに変えるとsetter, getterもポインタ返すように変えるべきでしょうか？

2021-03-05 00:44 UTC, TrainCoffeeBoy commented on Session.hpp
> +		void	setConfig();
void setConfig(const std::list<LocationConfig>& config_list);としました

2021-03-05 00:56 UTC, TrainCoffeeBoy commented on Response.hpp
> +  size_t getRawResponse(char**) const;
size_t getRawResponse(char**) const;
これが何者かよくわからないです。 std::string raw_response_;をgetするためにchar**を引数にするということは、key?みたいなものを使うイメージでしょうか？（暫定でchar** keysを引数にしてみました）

2021-03-05 00:58 UTC, TrainCoffeeBoy commented on Request.hpp
> +  std::string getBody() const;
gyoi!

2021-03-05 00:58 UTC, TrainCoffeeBoy commented on CgiHandler.hpp
> +		int	cgi_output_fd_;
消しました

2021-03-05 01:02 UTC, TrainCoffeeBoy commented on CgiHandler.hpp
> +};
getterで満足してました。追加しました。

2021-03-05 01:07 UTC, TrainCoffeeBoy commented
自信のないところ、見ていただきたいところはcomment resolveしないようにしてあります。

2021-03-05 01:19 UTC, dai65527 commented on LocationConfig.hpp
> +  void setIndex(std::list<std::string>);
OKです！ありがとうございます！

2021-03-05 01:19 UTC, dai65527 commented on LocationConfig.hpp
> +  void setCgiExtension(std::list<std::string>);
OKです！ありがとうございます！

2021-03-05 01:36 UTC, dai65527 commented on Session.hpp
> +		const LocationConfig&	config_;
とりあえず、

- setConfig: list<LocationConfig>のconst参照
- getConfig戻り値: LocationConfigの const参照

で良いと思います。これで問題はないかと。（あれば変更は容易かと思います）

> constついていると初期化してやらないといけないのは変わらないですね。

const pointerであれば大丈夫です。pointerの指す先のデータを変えられないだけなので。（以下サンプル）

```cpp
#include <iostream>

class Hoge {
private:
    const int* val;
public:
    void setVal(const int& ref) { val = &ref; }
    const int& getVal() const { return *val; }
};

int main(void)
{
    int val = 42; 
    Hoge hoge;

    hoge.setVal(val);
    std::cout << hoge.getVal() << std::endl;
    val = 21; 
    std::cout << hoge.getVal() << std::endl;

    return 0;
}
```

2021-03-05 01:46 UTC, dai65527 commented on Response.hpp
> +  size_t getRawResponse(char**) const;
すみません、分かりづらくて...
出来上がったレスポンスを送信するときに必要と思い作っていました。

socket経由で送る場合は、細切れに送られる可能性があるので、
raw_response_メンバの文字列ポインタに加え、何文字目まで送信が終了したかを知る必要があると思いこんな構成にしました。
`size_t getRawResponse(char** ptr_to_response_buffer) const;` みたいな感じにして、使うイメージです。引数のダブルポインタをresponseの生データに書き換えて、返り値にbyte_already_sent_を突っ込むみたいな感じです。

ただ、今見るとこれ使いにくそう...ですね...
普通にgetRawResponseは
`const char* getRawResponse() const` と `size_t getByteAlreadySent() const` を作って使う方がシンプルで分かりやすいかもしれません。

あるいは、引数にfdをとってResponseから送るというのもアリかもしれません。

2021-03-05 01:49 UTC, TrainCoffeeBoy commented on Session.hpp
> +		const LocationConfig&	config_;
なんと！知らないことばかり...ありがとうございます。勉強になります。

2021-03-05 02:38 UTC, TrainCoffeeBoy commented on Response.hpp
> +  size_t getRawResponse(char**) const;
```
  const char* getRawReponse() const;
  void incrementBytesAlreadySent(size_t bytes);
```
getRawReponse()でraw_response_.c_str()を返す。
そのときの先頭位置はsendされたsize_t bytesにより、
`size_t bytes_already_sent_;`
をインクリメントしてずらしながら行う。

2021-03-05 04:24 UTC, dai65527 commented on Session.hpp
> +  int setFdToSelect(fd_set rfds, fd_set wfds);
ポインタ渡しにしないと内容が書き換えられませんね。

2021-03-05 04:24 UTC, dai65527 commented on Session.hpp
> +  int readToFromFile();
readFromFile

2021-03-05 04:24 UTC, dai65527 commented on Session.hpp
> +  int checkSelectedAndExecute();
こちらもfdsを受け取らないとselectされているかの判断がつきませんね

2021-03-05 04:24 UTC, dai65527 commented on SessionStatus.hpp
> +typedef enum {
すみません直ってないっぽいです。。。🙇‍♂️

2021-03-05 04:24 UTC, dai65527 commented on CgiHandler.hpp
> +  int getCgiOutputFd() const;
すみません。こちらからもCgi外してしまいましょうか。

2021-03-05 04:25 UTC, dai65527 reviewed
確認しました！修正ありがとうございました。

一部未修正と若干直したい点があったのでコメントさせていただきました。
お手数ですが、修正をよろしくお願いいたします。

2021-03-05 11:29 UTC, TrainCoffeeBoy commented on CgiHandler.hpp
> +  int getCgiOutputFd() const;
OKです

2021-03-05 11:39 UTC, TrainCoffeeBoy commented on Session.hpp
> +  int checkSelectedAndExecute();
両方pointerにしました

2021-03-05 11:43 UTC, merged

2021-03-05 11:43 UTC, dai65527 commented
お忙しい中、細かい点まで修正していただきありがとうございました！
確認しました！これを元に実装に入れればと思います！