Create cgi process
dai65527/webserv pull request #25
Opened 2021-04-13 05:45 UTC by TrainCoffeeBoy

まだ途中ですが、mtgやりやすいようにPR出しておきます。
*テストかけてません

- queryをmapからstringに変更（処理をcgi側に任せるため）
- cgiに渡す環境変数を実装(AUTH_TYPE, GATEWAY_INTERFACE, REMOTE_IDENT, REMOTE_USERは未了）
- cgiにコマンドライン引数を渡す実装(XXX.cgi/argv1/argv2 かXXX.cgi?argv1+argv2の両方に対応）http://www.tohoho-web.com/wwwcgi3.htm#CgiParameter
- cgiにPOSTでbodyを渡す実装

実行例は以下の通りです。
`./nginDX configfiles/has_cgi.conf `
を実行したのち、
GETの場合、
```
$ telnet localhost 8888
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /sample.cgi?aaa+bbb HTTP/1.1
host:localhost

HTTP/1.1 200 OK
Server: nginDX
Content-Type: text/html
Content-Length: 925

<h1>cgi not yet implemented: ./html/sample.cgi</h1>
Content-type: text/html

<HTML>
<HEAD>
<TITLE>CGI TEST</TITLE>
</HEAD>
<BODY BGCOLOR='#FFFFFF' TEXT='#000000'>
<XMP>
=================================
コマンド引数
=================================
ARGV[0] = [ aaa ]
ARGV[1] = [ bbb ]

=================================
環境変数
=================================
AUTH_TYPE = [  ]
CONTENT_LENGTH = [  ]
CONTENT_TYPE = [  ]
GATEWAY_INTERFACE = [  ]
PATH_INFO = [  ]
PATH_TRANSLATED = [ ./html ]
QUERY_STRING = [ aaa+bbb ]
REMOTE_ADDR = [ 127.0.0.1 ]
REMOTE_IDENT = [ TEST ]
REMOTE_USER = [ TEST ]
REQUEST_METHOD = [ GET ]
REQUEST_URI = [ /sample.cgi ]
SCRIPT_NAME = [ /sample.cgi ]
SERVER_NAME = [ localhost ]
SERVER_PORT = [ 8888 ]
SERVER_PROTOCOL = [ HTTP/1.1 ]
SERVER_SOFTWARE = [ nginDX ]

=================================
フォーム変数
=================================
aaa+bbb = 
</XMP>
</BODY>
</HTML>

Connection closed by foreign host.
```
POSTの場合
```
$ telnet localhost 8888
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
POST /sample.cgi?aaa=bbb&ccc=ddd HTTP/1.1
host:localhost
content-length:12

<h1>Hi!</h1>
HTTP/1.1 200 OK
Server: nginDX
Content-Type: text/html
Content-Length: 902

<h1>cgi not yet implemented: ./html/sample.cgi</h1>
Content-type: text/html

<HTML>
<HEAD>
<TITLE>CGI TEST</TITLE>
</HEAD>
<BODY BGCOLOR='#FFFFFF' TEXT='#000000'>
<XMP>
=================================
コマンド引数
=================================

=================================
環境変数
=================================
AUTH_TYPE = [  ]
CONTENT_LENGTH = [ 12 ]
CONTENT_TYPE = [  ]
GATEWAY_INTERFACE = [  ]
PATH_INFO = [  ]
PATH_TRANSLATED = [ ./html ]
QUERY_STRING = [ aaa=bbb&ccc=ddd ]
REMOTE_ADDR = [ 127.0.0.1 ]
REMOTE_IDENT = [ TEST ]
REMOTE_USER = [ TEST ]
REQUEST_METHOD = [ POST ]
REQUEST_URI = [ /sample.cgi ]
SCRIPT_NAME = [ /sample.cgi ]
SERVER_NAME = [ localhost ]
SERVER_PORT = [ 8888 ]
SERVER_PROTOCOL = [ HTTP/1.1 ]
SERVER_SOFTWARE = [ nginDX ]

=================================
フォーム変数
=================================
<h1>Hi!</h1>
</XMP>
</BODY>
</HTML>

Connection closed by foreign host.
```

2021-04-13 11:40 UTC, dai65527 commented on Session.cpp
> +  tmp = "AUTH_TYPE=";
char**を返すようにした方がシンプルかも？

2021-04-13 11:58 UTC, dai65527 reviewed
引き続きお願いします！

2021-04-13 11:58 UTC, dai65527 commented on Session.cpp
> +  uint32_t tmp;
utils or libftに追加の方が良い？

2021-04-13 15:42 UTC, TrainCoffeeBoy commented on Session.cpp
> +  uint32_t tmp;
utilsに移しました。

2021-04-14 14:21 UTC, TrainCoffeeBoy commented on Session.cpp
> +  tmp = "AUTH_TYPE=";
そうしました。

2021-04-15 16:10 UTC, TrainCoffeeBoy commented
コメントいただいたところの修正、テストの作成をしました。
ご確認お願いします。

2021-04-15 16:58 UTC, TrainCoffeeBoy commented
keep-alive実装の分をmergeしました

2021-04-16 03:12 UTC, dai65527 requested changes
コメントしました。大枠OKだと思います。
以下、ご確認、修正願えますでしょうか。

- argvの仕様気になったところがありました
  - `/hoge/fuga.cgi/arg1/arg2` などのパターン
- readFromCgi関数内で、cgiが出力したレスポンスヘッダのパースや足りないヘッダの追加が必要そうです
- malloc使用関数のNULLチェック
  - strdupやsplitなど
  - 失敗時は例外投げる感じで良いと思います（あとでまとめて処理する方法を考える方針）
- DirectoryListing消えてますね。
- その他細かいコメントしたので適宜反映をお願いします。

よろしくお願いします！

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
> +  uint16_t port_ = 0x1234;
変数宣言不要ですね。

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
> -  }
ディレクトリリスティング消えてる...??

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
> +  response_.appendToBody("</h1>\n", 6);
マージできてないかもです。ご確認願います。（MTGのときでも！）

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
> +  char** meta_variables = storeMetaVariables(cgiuri);
nullチェック必要そうです。でもstroreArgvでbad_alloc例外投げた方がいいかもしれません。
いずれどこかで例外処理が必要なので

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
> +  return ft_split(argv.c_str(), '/');
uriが`/hoge/fuga.cgi/arg1/arg2` などの場合に対応できない気がします。

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
> +    return ft_split(argv.c_str(), '+');
nullチェックをしてダメならbad_allocを投げると良いと思います。他のコンテナクラスも例外を投げる可能性があるので、いずれどこかでキャッチする機構を作らないといけませんね...

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
>    response_.appendToBody("</h1>\n", 6);
不要かと思います！

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
> +  }
PUTでCGI動くんでしたっけ

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
> +  tmp += path_info;
`tmp += getPathInfo(cgiuri);`

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
> +  tmp += std::string(server_port);
一度stringのインスタンスを作ってoperator+=を使うより、char*からappend関数を使った方が効率が良さそうです。

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
> +  char* server_port = ft_itoa(ft_htons(port_));
nullチェック

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
> +  }
bad_alloc例外投げてどこかでまとめてキャッチするほうが良さそうです。キャッチする場所はまた考えるとして。

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
> +    meta_variables[i] = ft_strdup(envp[i].c_str());
nullチェック

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
> +  std::vector<std::string> envp;
とっても細かいのですが、envpだとポインタを想定してしまい少し混乱しました。meta_variablesとかでもいいかもしれません。

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
> +  char** meta_variables = (char**)malloc(sizeof(char*) * (envp.size() + 1));
こっちをenvpにした方がしっくりきますね...（細かい...すみません...）

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
> +  free(meta_variables);
argvも同様に中身までfree必要ですね！

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
> +  return path_info;
`path_info = request_.getUri().substr(cgiuri.length, request_.getUrl().length())`的にやると、eraseしなくて少し早そうですね（少し）

2021-04-16 03:12 UTC, dai65527 commented on test/unit_test/Session/test_CgiArgvEnvp.cc
> +
`/hoge/fuga.cgi?aaa+bbb+ccc`や`/hoge/fuga.cgi/aaa/bbb/ccc`のようなケースもありそうですね。

2021-04-16 03:12 UTC, dai65527 commented on test/unit_test/webserv_utils/test_getIpAddress.cc
> +  EXPECT_EQ(getIpAddress(-1), "255.255.255.255");
inet_addrの逆関数なので、
`EXPECT_EQ(getIpAddress(inet_addr("127.0.0.1"), "127.0.0.1")`
のようにテストするとわかりやすいかなと思います！

2021-04-16 03:12 UTC, dai65527 commented on webserv_utils.cpp
> +      free(tmp);
nullチェック

2021-04-16 03:12 UTC, dai65527 commented on webserv_utils.cpp
> +      tmp = ft_itoa(ip_array[i]);
nullチェック

2021-04-16 03:12 UTC, dai65527 commented on Session.cpp
>  }
readFromCgi関数内で、

- cgiが出力したレスポンスヘッダのパース
- 足りないヘッダの追加

の処理が必要かと思います。

2021-04-16 04:47 UTC, TrainCoffeeBoy commented on Session.cpp
> +  uint16_t port_ = 0x1234;
ですね

2021-04-16 04:48 UTC, TrainCoffeeBoy commented on Session.cpp
> -  }
復活させました（すみませんでした。まだgitが使いこなせてないです...）

2021-04-16 04:49 UTC, TrainCoffeeBoy commented on Session.cpp
> +  response_.appendToBody("</h1>\n", 6);
こちらも対応しました

2021-04-16 04:55 UTC, TrainCoffeeBoy commented on Session.cpp
> +  char** meta_variables = storeMetaVariables(cgiuri);
NULLでも後工程動くのでどうしようかなと思っていました。
例外処理の先でServerのInternal Errorを返すべきかなと思うようになりました。

2021-04-16 04:56 UTC, TrainCoffeeBoy commented on Session.cpp
> +    return ft_split(argv.c_str(), '+');
これもNULLでも後工程動くのでどうしようかなと思っていました。
例外処理の先でServerのInternal Errorを返すべきかなと思うようになりました。

2021-04-16 04:56 UTC, TrainCoffeeBoy commented on Session.cpp
>    response_.appendToBody("</h1>\n", 6);
削除済みです

2021-04-16 05:02 UTC, TrainCoffeeBoy commented on Session.cpp
> +  }
wikiなどではpost or putでstdinからというような記述がありますね。
https://en.wikipedia.org/wiki/Common_Gateway_Interface
rfcだとextension methodとして記述ありです
https://tools.ietf.org/html/rfc3875

2021-04-16 05:03 UTC, TrainCoffeeBoy commented on Session.cpp
> +  tmp += path_info;
PATH_TRASLATEDでまたpath_infoを使うので一旦インスタンス作って見たのですが、
getPathInfoをもう一回呼ぶ方が効率がいい感じですか？

2021-04-16 05:06 UTC, TrainCoffeeBoy commented on Session.cpp
> +  std::vector<std::string> envp;
そのように修正します

2021-04-16 05:07 UTC, TrainCoffeeBoy commented on Session.cpp
> +  char** meta_variables = (char**)malloc(sizeof(char*) * (envp.size() + 1));
御意

2021-04-16 05:07 UTC, TrainCoffeeBoy commented on Session.cpp
> +  free(meta_variables);
忘れてた...直します

2021-04-16 05:08 UTC, TrainCoffeeBoy commented on test/unit_test/webserv_utils/test_getIpAddress.cc
> +  EXPECT_EQ(getIpAddress(-1), "255.255.255.255");
なるほど！直します

2021-04-16 14:01 UTC, TrainCoffeeBoy commented on Session.cpp
> +  return ft_split(argv.c_str(), '/');
直しました

2021-04-16 14:27 UTC, TrainCoffeeBoy commented on Session.cpp
> +  char* server_port = ft_itoa(ft_htons(port_));
throw std::bad_allocしておきます

2021-04-16 15:01 UTC, TrainCoffeeBoy commented on test/unit_test/Session/test_CgiArgvEnvp.cc
> +
足しました！

2021-04-19 11:29 UTC, TrainCoffeeBoy commented on Session.cpp
> +    if (!ft_strncmp(read_buf + i, "\n\n", 2)) {
or 条件で\r\n\r\nもキャッチする

2021-04-19 11:29 UTC, TrainCoffeeBoy commented on Session.cpp
> +  char** argv = storeArgv(filepath, cgiuri);
argvのクラスを作り、destructorでfreeする

2021-04-19 11:55 UTC, TrainCoffeeBoy commented on Session.cpp
> +  response_.appendToBody(read_buf + end_header + 1, n - (end_header + 1));
read_bufで読み込みキレなくても、bodyにappendされていくのでOK。
headerが終わってるかどうかのflgで場合分けが必要。
headerはaddResponseHeaderを塊で渡せるように改造すればいい。

2021-04-19 15:08 UTC, TrainCoffeeBoy commented on Session.cpp
> +  char** argv = storeArgv(filepath, cgiuri);
done

2021-04-21 01:50 UTC, TrainCoffeeBoy commented on Session.cpp
> +  response_.appendToBody(read_buf + end_header + 1, n - (end_header + 1));
read_bufがheader途中で切れる場合など面倒なので、cgi_handlerにvector<char> but_を作り、そこに全てためてからparseするように変更。headerはparser内でmapに入れ、エラーがなければ、各headerに対してaddResponseHeaderをそのまま使うとした。

2021-04-21 13:10 UTC, TrainCoffeeBoy commented
- Session classのなかにCgiPrams classを作り, mallocをwrapし、freeをdestructor任せにしました
- SessionのreadFromCgiの中身の一部をCgiHandlerに移管、またchar* read_buf[1024]で読んだ内容をvector<char>に保存していき、全て読みきった後にparseするように変更
- parseではheaderをmapに保存し、エラーチェックののちに、header（もしくはstatus)に追加。
コンフリクトは他のPR をmergeしたのちに直します。mergeはその後でお願いします。

2021-04-21 13:18 UTC, TrainCoffeeBoy commented
- Session classのなかにCgiPrams classを作り, mallocをwrapし、freeをdestructor任せにしました
- SessionのreadFromCgiの中身の一部をCgiHandlerに移管、またchar* read_buf[1024]で読んだ内容をvectorに保存していき、全て読みきった後にparseするように変更
- parseではheaderをmapに保存し、エラーチェックののちに、header（もしくはstatus)に追加。
- status codeの指定はnginxの挙動に合わせた（"Status: code SP reason" という記法があるが、code以下に対して厳密なエラーチェックはない）

コンフリクトは他のPR をmergeしたのちに直します。mergeはその後でお願いします。

2021-04-21 16:02 UTC, TrainCoffeeBoy commented
conflict解消のため、mergeし、Dateのheaderがcgiのresponseでstatus code書き換えでも出力されるようにしました。
Charsetについても、対応が必要ですが、ちょっと混乱中です。

2021-04-21 23:33 UTC, TrainCoffeeBoy commented
Dateヘッダーを出すようにして、unit_testについて、failしますが未対応デス。

2021-04-22 03:05 UTC, dai65527 requested changes
大変なところありがとうございました。cgiヘッダのパース、CgiParamsなど参考になりました！

全体的に確認しました。動作も基本OKだと思います。
細かいところだけいろいろコメントさせていただきました。
すみませんが、修正をお願いいたします！

2021-04-22 03:05 UTC, dai65527 commented on Session.cpp
> +
CgiParams.cppなどの別ファイルに切り出しましょう。

2021-04-22 03:05 UTC, dai65527 commented on Session.hpp
> +  };
CgiParams.hppという別ファイルに切り出した方が良いかなと思いました！

2021-04-22 03:05 UTC, dai65527 commented on Session.cpp
> +  std::string argv = filepath;
argvだとargv_と被って混乱しやすいかもしれません...

2021-04-22 03:05 UTC, dai65527 commented on Session.cpp
> +    argv_ = ft_split(argv.c_str(), '+');
filepathの中に+が入っていたら...（可能性は低いと思いますが）

2021-04-22 03:05 UTC, dai65527 commented on Session.cpp
> +    argv_ = ft_split(argv.c_str(), '+');
こんな感じじゃダメですかね？

```cpp
argstr = "dummy+"
argstr += request.getQuery();
argv = ft_split(argstr.c_str(), '+');
free(argv[0]);
argv[0] = strdup(filepath.c_str());
```

2021-04-22 03:05 UTC, dai65527 commented on Session.cpp
> +  return argv_ + begin;
ここも流石にややこしい気がします。
上と同様にfilepathのところはダミーを入れておく、でもいい気がします。

```cpp
argstr = "dummy" + session_.getPathInfo();
argv = ft_split(argstr.c_str(), '/');
free(argv[0]);
argv[0] = strdup(filepath.c_str());
```

2021-04-22 03:05 UTC, dai65527 commented on Session.cpp
> +  }
throw bad_allocの方が良いですね。
（どこかでto_string実装するつもりです。笑）

2021-04-22 03:05 UTC, dai65527 commented on Session.cpp
> +  }
了解です！（Session側実装しないとですね）

2021-04-22 03:05 UTC, dai65527 commented on Session.cpp
> +    while (read_buf[i] > 31 && read_buf[i] != 127 &&
isprintを使うと可読性が高いかと思います！

2021-04-22 03:05 UTC, dai65527 commented on Session.cpp
> +      header.find("Location") != header.end() || status_itr != header.end()) {
小文字/大文字の混在は許されないのですか？

2021-04-22 03:05 UTC, dai65527 commented on Response.cpp
> +  status_header_.append(value);
値はなんでも受け入れるでOKですかね？

2021-04-22 03:05 UTC, dai65527 commented on Session.cpp
> +  return -1;  // find No valid header
（細かいですが！）最初に`if (/* case no valid header */) return;`とした方が可読性は良い気がします。

2021-04-22 03:05 UTC, dai65527 commented on Session.cpp
>      return 0;
いらないかも

2021-04-22 03:05 UTC, dai65527 commented on Session.hpp
> +#define SESS_FIN_PARSE_CGI_HEADER 1
不要？

2021-04-22 03:05 UTC, dai65527 commented on Session.cpp
operator=ごと消して良いかと思います！

2021-04-22 03:05 UTC, dai65527 commented on CgiHandler.cpp
>      exit(1);
execveの失敗ケースは、pipeからの出力がない→502が返るで意図した挙動になってますかね？

2021-04-22 03:05 UTC, dai65527 commented on test/unit_test/Session/test_CgiResponse.cc
> +
Dateヘッダー...
飛ばしてテストするのが良いのかな。
あるいは...
っhttp://opencv.jp/googletestdocs/advancedguide.html#adv-regular-expression-syntax

2021-04-22 03:05 UTC, dai65527 commented on test/unit_test/Session/test_CgiArgvEnvp.cc
> +}
改行欲しいです！

2021-04-22 03:05 UTC, dai65527 commented on CgiHandler.cpp
> +const std::vector<char>& CgiHandler::getBuf() const { return buf_; }
bufの内容をクリアする関数をSession::resetAllから呼び出すようにした方が良いと思います。
responseを送信した後にbufをクリアしないと、keepaliveの2回目でbufの中身に追加された形で出てきてしまいます。

2021-04-22 03:05 UTC, dai65527 commented on html/sample.cgi
> +print "Content-Type: text/html\n";
ブラウザで文字化けしてしまうので、
`test/html; charset=utf-8`
にしていただけると嬉しいです！

2021-04-22 11:05 UTC, TrainCoffeeBoy commented on Session.hpp
> +  };
sessionのgetterをpublicにした上で、別ファイルに切り出す

2021-04-22 11:14 UTC, TrainCoffeeBoy commented on Session.cpp
> +    while (read_buf[i] > 31 && read_buf[i] != 127 &&
cstring

2021-04-22 11:15 UTC, TrainCoffeeBoy commented on Session.cpp
> +      header.find("Location") != header.end() || status_itr != header.end()) {
RFCでは許されないようです。

2021-04-22 11:18 UTC, TrainCoffeeBoy commented on Response.cpp
> +  status_header_.append(value);
nginxに合わせてます

2021-04-22 11:18 UTC, TrainCoffeeBoy commented on Session.cpp
> +  return -1;  // find No valid header
承知です！

2021-04-22 11:20 UTC, TrainCoffeeBoy commented on Session.cpp
>      return 0;
1243いらない！

2021-04-22 11:20 UTC, TrainCoffeeBoy commented on Session.hpp
> +#define SESS_FIN_PARSE_CGI_HEADER 1
消し忘れた...

2021-04-22 11:21 UTC, TrainCoffeeBoy commented on Session.cpp
消します

2021-04-22 11:29 UTC, TrainCoffeeBoy commented on CgiHandler.cpp
>      exit(1);
特に対応不要でした

2021-04-22 11:32 UTC, TrainCoffeeBoy commented on test/unit_test/Session/test_CgiArgvEnvp.cc
> +}
L150に\n

2021-04-22 11:34 UTC, TrainCoffeeBoy commented on CgiHandler.cpp
> +const std::vector<char>& CgiHandler::getBuf() const { return buf_; }
CgiHandlerのmethodでresetall作って、それをsessionのresetallで呼ぶべし

2021-04-22 11:34 UTC, TrainCoffeeBoy commented on html/sample.cgi
> +print "Content-Type: text/html\n";
入れときます

2021-04-22 13:42 UTC, TrainCoffeeBoy commented on Session.cpp
> +
done

2021-04-22 13:51 UTC, TrainCoffeeBoy commented on Session.cpp
> +    argv_ = ft_split(argv.c_str(), '+');
いただきます！

2021-04-22 13:56 UTC, TrainCoffeeBoy commented on Session.cpp
> +  return argv_ + begin;
いただきました

2021-04-22 13:56 UTC, TrainCoffeeBoy commented on Session.cpp
> +  std::string argv = filepath;
argstrとしました

2021-04-22 14:12 UTC, TrainCoffeeBoy commented on test/unit_test/Session/test_CgiResponse.cc
> +
Dateヘッダーを飛ばすようにしました
```
  #ifndef UNIT_TEST
  addHeader("Date", buf);
  #endif
```

2021-04-22 14:33 UTC, TrainCoffeeBoy commented
コメントいただいたところを修正しました。確認をお願いします。

2021-04-23 00:58 UTC, dai65527 commented on test/unit_test/Session/test_CgiResponse.cc
> +
なるほど笑

2021-04-23 01:54 UTC, dai65527 approved these changes
お疲れ様です！ほぼほぼLGTMです！
少しコメントしました。直したらセルフマージでお願いします！

2021-04-23 01:54 UTC, dai65527 commented on test/unit_test/Session/test_CgiResponse.cc
> +}
改行

2021-04-23 01:54 UTC, dai65527 commented on CgiParams.cpp
> +  }
ここ不要？

2021-04-23 01:54 UTC, dai65527 commented on Request.cpp
> +// }
消しちゃいますか？

2021-04-23 04:54 UTC, TrainCoffeeBoy commented on CgiParams.cpp
> +  }
消すの忘れてた...

2021-04-23 05:00 UTC, merged