Mod request decode trace
dai65527/webserv pull request #46
Opened 2021-04-30 14:36 UTC by TrainCoffeeBoy

### Requestの修正
以下の３点の修正をしました。unit_test, integrate_testを実施しています。ft_testerもOKです。
- chunkで0が来たらすぐにparseを終える（ft_testerの仕様に合わせた）
- URLデコードをURI, queryに適用
- TRACEを実装
 - headerのparseが終わった時点で、body_にbuf_の内容を突っ込むようにしました。
 - content-type: message/http をresponseするようにRFCに明記あり、関係する関数をいじりました
 - TRACEで禁止されるheaderの組み合わせはRFC上には明記なく、content-length, chunkedなどをそのままheaderとしては取得し、bodyは無視するようにしました(APACHEではエラーを出す実装になっていましたが）
 
確認、よろしくお願いします。

2021-05-01 01:09 UTC, dai65527 requested changes
ご対応ありがとうございました！概ねLGTMです！
ただ、42Testerで0chunkedの後続のHEADがおかしくなっているように見えます。原因を探ってみていますが、まだピンと来ていません。

あと、テストケースの追加、ファイル末尾の改行をお願いします。

2021-05-01 01:09 UTC, dai65527 commented on test/integration_test/my_tester/main.rb
> +#####
パーセントエンコーディングのテスターも追加お願いいたします！

```ruby
casename = "get /ファイル名.html in percent encoding"
testcase = WebservTestCase.new casename, "127.0.0.1", 8000, "/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%90%8D.html", "GET"
testcase.expectedCode = "200"
testcase.expectedBody = "<h1>日本語でおk</h1>\n".force_encoding("ASCII-8BIT")  # need to change encoding to compare results
testcase.expectedResponseHeader["Server"] = "nginDX"
testcase.expectedResponseHeader["Content-Length"] = testcase.expectedBody.length.to_s
testcase.expectedResponseHeader["Connection"] = "keep-alive"
testcase.expectedResponseHeader["Content-Type"] = "text/html"
testcase.expectedResponseHeaderExistance.push "Date"
testcase.expectedResponseHeaderExistance.push "Last-Modified"
testcase.add
```

test/integration_test/my_tester/html/default_server/ファイル名.html

```
<h1>日本語でおk</h1>
```

2021-05-01 01:09 UTC, dai65527 commented on test/unit_test/ParseRequest/test_parseRequest.cc
> +}
改行

2021-05-01 01:09 UTC, dai65527 commented on Request.cpp
> +          return REQ_FIN_RECV;
この変更（おそらく）で42testerの後続のテストケースでエラーが出てしまうようです。バグの原因を探していますが、まだピンと来ません。

2021-05-01 11:53 UTC, TrainCoffeeBoy commented on test/integration_test/my_tester/main.rb
> +#####
げえ、mergeした時に消えちゃったのか（飲酒運転ダメだ...)
足しておきます。

2021-05-01 12:48 UTC, TrainCoffeeBoy commented on test/integration_test/my_tester/main.rb
> +#####
笑, done!

2021-05-02 13:12 UTC, dai65527 approved these changes
LGTMです！ありがとうございました！！！

2021-05-02 13:12 UTC, merged