Mod cgi add cgipath directive
dai65527/webserv pull request #47
Opened 2021-05-01 05:37 UTC by dai65527

CGI修正しました！ご確認をよろしくお願いいたします。

### 修正点
- cgi_passディレクティブを追加
  - cgi_passディレクティブが指定されている場合、cgi_extensionにマッチするルートがきたらそのファイルを呼び出す。
- CGIに渡すメタ変数にPATH_INFOを追加。
  - テスター対応
  - cgiのurlを入れるのみ
  - cgi_passディレクティブが指定されている場合も元のurlを使用する
- その他修正
  - POST/PUT時にcgiの実行ファイルの場所をlocationを考慮して決定するよう修正（Session.cpp, L374。GETは修正済み）
  - readのエラー処理場所を微修正

### テスト
#### 単体テスト
新しく加えたディレクティブ と今回の修正に応じて変更をかけています。

#### 統合テスト
main.rbにCGIのテストを追加しました。
  - 42のCGIテスター(cgi_tester)の動作テスト
  - 自前のスクリプトを使用したテスト

2021-05-01 14:33 UTC, TrainCoffeeBoy requested changes
CgiParamsの元々のPATH_INFOが不要になると思いますので確認お願いします。

2021-05-01 14:33 UTC, TrainCoffeeBoy commented on CgiParams.cpp
> +  meta_variables.push_back("PATH_INFO=" + cgiuri);
元々あるPATH_INFOのL75〜は、合わせて削除した方が良いって事ですね。

2021-05-01 14:33 UTC, TrainCoffeeBoy commented on Session.cpp
> +    return -1;
こっちの方が分かりやすいですね！

2021-05-01 14:33 UTC, TrainCoffeeBoy commented on Session.cpp
> +    }
テストケース甘かったですね、自分。改良ありがとうございます。

2021-05-01 14:33 UTC, TrainCoffeeBoy commented on CgiParams.cpp
> +  meta_variables.push_back("PATH_INFO=" + cgiuri);
これがslackに書いてあった件ですね。

2021-05-01 22:25 UTC, dai65527 commented on CgiParams.cpp
> +  meta_variables.push_back("PATH_INFO=" + cgiuri);
見逃していました...

2021-05-01 23:24 UTC, dai65527 commented
以下修正しました。ご確認よろしくお願いいたします！

- PATH_INFO重複→解消しました。
- CgiParamsのAUTH_TYPE、REMOTE_IDENT、REMOTE_USERを更新しました。
  - AUTH_TYPE: Basic
  - REMOTE_USER: Base64デコード済ユーザ名のみ（`user:pass`の`user`のみ）
  - REMOTE_IDENT: 現状はREMOTE_USERと同じものを入れています。（答えはなさそうです。ユーザIDと判断して、ユーザ名を入れることにしました）

2021-05-02 12:17 UTC, TrainCoffeeBoy approved these changes
LGTMです。ありがとうございます！

2021-05-02 12:17 UTC, merged