LogFeeder
dai65527/webserv pull request #51
Opened 2021-05-03 17:23 UTC by TrainCoffeeBoy

NginxのLogを真似して、stdoutにlogを出力するクラスを作成しました。
一旦、PR出させていたきます。

nginxのlog formatの基本は以下の通りです。
```
log_format combined '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent"';
```
nginDXではtime_localではなく、GMTをそのまま使っています。

Session.cppでsendResponseが終わった後に、resetAll()する前にLogFeederでlogを出します。
status codeを返す際にcgiでの出力にも対応が必要なので、Responseの中身から200などを取得するようにしました。
それに伴い、Responseの中身を修正しています(sendData内のheaderのclearなどを削除し、resetAll()に任せた)。

以下のような形で出力されます。
`127.0.0.1 - user [Mon, 03 May 2021 16:59:35 GMT] "GET /needauth/index.html HTTP/1.1" 200 22 "-" "Ruby"`
`127.0.0.1 - - [Mon, 03 May 2021 17:08:39 GMT] "GET / HTTP/1.1" 200 729 "-" "curl/7.65.3"`

LogFeederのためのtest caseはまだ作っていません（どうやって作ろう?）が、
既存のテストケース(my tester, unit test）はOKです(ft_testerは現在最後のケースがまだ走ってます...)。

2021-05-03 22:44 UTC, dai65527 requested changes
Nginx風の見やすいログで素晴らしいと思います！ありがとうございました！
以下、コメントしました。ご確認と修正をお願いいたします！

### コード中にコメント
- Session、Request、Responseを保持するが、Sessionのみで良いのでは？
- LogFeederはSessionのメンバに持たせれば良さそう。
- フォーマット崩れ（フォーマッタ1発で解決すると思います）

### その他
- 各所にある`[webserv] hogehoge`といったコメントは消してもいいかもしれません。
- 時間のかかる処理があるので、AcceptとSentの2つのタイミングでなんらかの情報を出してやるとレビュー時に親切かもしれません（Requst情報とResponse情報の出すタイミングを分けるなど？）

2021-05-03 22:44 UTC, dai65527 commented on LogFeeder.hpp
> +	const Response& response_;
インデント

2021-05-03 22:44 UTC, dai65527 commented on LogFeeder.hpp
> +	std::string getRemoteUser() const;
インデント

2021-05-03 22:44 UTC, dai65527 commented on Response.cpp
>          return 0;            // end
resetAllでやるほうがいいですね。ありがとうございます。

2021-05-03 22:44 UTC, dai65527 commented on Response.cpp
> +
スペース入ってますね。

2021-05-03 22:44 UTC, dai65527 commented on Session.cpp
> +    logfeeder.feedLog();
LogFeederに関してはSessionのメンバに持たせておけばいいと思います！毎回宣言するのも大変なので。

2021-05-03 22:44 UTC, dai65527 commented on Session.cpp
> +    logfeeder.feedLog();
ログを吐く場所を追加したい時にもそのほうが便利だと思います。

2021-05-03 22:44 UTC, dai65527 commented on LogFeeder.cpp
> +                     const Response& response)
Sessionを渡すのみでよいかもしれません。1つの情報に複数のアクセスルートがあるのに違和感がありますし、あとで少し混乱するかもしれません（「引数のRequestとSessionのRequestは別のものじゃなきゃいけないの？」など）
必要であればSessionにGetter追加すればいいと思います。
（CGIParamsにも同じようなところがありましたが、今回は修正不要と思います）
（循環参照辛いですが仕方ないですね。）

2021-05-04 13:01 UTC, TrainCoffeeBoy commented on Session.cpp
> +    logfeeder.feedLog();
LogFeederのpoiterをメンバにし、Session constructor で new, destructorでdelteするようにしました。引数ありコンストラクタの初期化がポインタでないとうまくいかなかったので（やり方他にあれば教えて欲しいです）。

2021-05-04 13:01 UTC, TrainCoffeeBoy commented on LogFeeder.cpp
> +                     const Response& response)
gettersを作り、sessionのみにしました。

2021-05-04 14:52 UTC, dai65527 commented on Session.cpp
> +    logfeeder.feedLog();
確かにSessionの参照を持つので、Sessionのコンストラクタでうまく初期化するのは難しいですね... 今の方法でOKとは思いますが、ちょっとうまい方法探してみます。
（こだわらなくていいところかもしれませんが、こだわりたくなっちゃう42Studentですね笑）

2021-05-04 15:01 UTC, TrainCoffeeBoy commented
> 時間のかかる処理があるので、AcceptとSentの2つのタイミングでなんらかの情報を出してやるとレビュー時に親切かもしれません（Requst情報とResponse情報の出すタイミングを分けるなど？）
request lineのparse直後にURIまで出力、sent後に全て出力で作って見ました。
凝ると色々できそうですが、まずはこの辺りで良いかと。

2021-05-04 21:53 UTC, dai65527 commented
ご対応ありがとうございました！

> > 各所にある[webserv] hogehogeといったコメントは消してもいいかもしれません。
ありがとうございます！

> > 時間のかかる処理があるので、AcceptとSentの2つのタイミングでなんらかの情報を出してやるとレビュー時に親切かもしれません（Requst情報とResponse情報の出すタイミングを分けるなど？）
> request lineのparse直後にURIまで出力（recvとして）、sent後に全て出力で作って見ました。
ありがとうございます。わかりやすいです！

> （たまにrecv側のIPの表示が127.0.0.1にならない時があります。今のところよくわからずです）
session::ip_の初期化はsetupServerAndLocationConfigの中で行われるので、その前に読んでもごみデータが入っているだけですね。setupServerAndLocationConfigの後ろに移動したらうまくいきます。
→これでpushしてマージしてしまいますね！

2021-05-04 22:06 UTC, dai65527 approved these changes
LGTM!!

2021-05-04 22:07 UTC, merged